config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  root "users#index"
  resources :users do
    get '/enroll_event/:event_id', to: 'users#enroll_event', as: 'enroll_event', on: :member
    get '/discard_enrolled_event/:event_id', to: 'users#discard_enrolled_event', as: 'discard_enrolled_event', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :users
  validates :event_name, :event_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  mount_uploader :profile, ProfileUploader
  attr_reader :old_email

  after_create :send_welcome_email, :create_employee
  has_one :employee, dependent: :destroy
  has_and_belongs_to_many :events
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, confirmation: true, length: { minimum: 6 }, if: :password_digest_changed?
  validates :profile, presence: true

  private

  def send_welcome_email
    SendEmailsJob.perform_now(self)
  end

  def create_employee
    CreateEmployeeJob.set(wait: 2.minutes).perform_later(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show edit update destroy enroll_event discard_enrolled_event]
  before_action :find_event, only: %i[enroll_event discard_enrolled_event]

  def index
    @users = User.all
  end

  def show
    @events = Event.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user), flash: { notice: "User was created successfully"}
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @old_email = @user.email
    if @user.update(user_params)
      UserMailer.with(user: @user, old_email: @old_email).changed_email.deliver_now if @old_email != @user.email
      redirect_to user_path(@user), flash: { notice: "Profile was updated successfully"}
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, flash: { notice: "User was deleted successfully"}
  end
  
  def enroll_event
    @user.events << @event
    redirect_to user_path(@user)
  end
  
  def discard_enrolled_event
    @user.events.destroy(@event)
    redirect_to user_path(@user)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :profile, :password, :password_confirmation)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def find_event
    @event = Event.find(params[:event_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def event_enrolled?(event)
    @user.events.include?(event)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionMailer</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/421bc9e4ef.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="container alert <%= flash.alert ? "alert-danger" : "alert-success" %> w-50 my-5">
        <%= msg %>
      </div>
    <% end %>
    
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
  </body>
</html>

app/views/layouts/custom.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
  <h3>This is custom layout</h3>
    <%= yield %>
  </body>
</html>

app/views/layouts/custom.text.erb
This is custom layout
<%= yield %>

app/views/users/_event.html.erb
<tr>
  <td><%= event.event_name %></td>
  <td><%= event.event_date %></td>
  <td>
    <% if event_enrolled?(event) %>
      <%= link_to "Discard", discard_enrolled_event_user_path(@user.id, event.id), class: "btn btn-danger rounded-1" %>
    <% else %>
      <%= link_to "Enroll", enroll_event_user_path(@user.id, event.id), class: "btn btn-info rounded-1" %>
    <% end %>
  </td>
</tr>

app/views/users/_form.html.erb
<div class="container mt-5" style="width: 700px;">
  <h2 class="my-3"><%= text %></h2>
  <%= form_with model: @user, id: "new_user" do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    
    <div class="mb-3">
      <%= form.label :email, class: "form-label" %>
      <%= form.text_field :email, class: "form-control" %>
    </div>
    <% if action_name == "new" %>
      <div class="mb-3">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :password_confirmation, class: "form-label" %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>
    <% end %>

    <div class="mb-4">
      <%= form.label :profile, class: "form-label" %>
      <%= form.file_field :profile, class: "form-control" %>
    </div>
    
    <%= form.submit "Sign up", class: "btn btn-success rounded-1" %>
    <%= link_to "Cancel", users_path, class: "btn btn-danger rounded-1 ms-2" %>
  <% end %>
</div>

app/views/users/_user.html.erb
<tr>
  <td><%= image_tag(user.profile_url, class: "rounded-circle", size: "50x50") %></td>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= link_to raw('<i class="fa-solid fa-eye fa-lg" style="color: #12e4f3;"></i>'), user_path(user), class: "btn p-0", title: "Show" %>
    <%= link_to raw('<i class="fa-solid fa-pen-to-square fa-lg" style="color: #f4e32a;"></i>'), edit_user_path(user), class: "btn p-0 ms-3", title: "Edit" %>
    <%= link_to raw('<i class="fa-solid fa-trash-can fa-lg" style="color: #f02828;"></i>'), user_path(user), class: "btn p-0 ms-3", title: "Remove", data: { turbo_method: :delete, turbo_confirm: :"Are You Sure?" } %></td>
</tr>

app/views/users/edit.html.erb
<%= render "form", text: "Update Profile" %>

app/views/users/index.html.erb
<div class="container mt-5 w-50">
  <div>
    <table class="table container table-hover table-striped">
      <thead>
        <tr>
          <th>Photo</th>
          <th>Username</th>
          <th>Email</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= render @users %>
      </tbody>
    </table>
  </div>

  <div class="mt-5">
    <%= link_to "Sign up", new_user_path, class: "btn btn-info me-3 px-3" %>
  </div>
</div>

app/views/users/new.html.erb
<%= render "form", text: "Registration" %>

app/views/users/show.html.erb
<div class="container my-5" style="width: 600px;">
  <div class="row">
    <div class="col-4">
      <%= image_tag @user.profile_url, class: "rounded-circle", size: "200x200" %>
    </div>

    <div class="col-2"></div>

    <div class="col-4 d-flex flex-column justify-content-around">
      <div>
        <h5><strong>Username:</strong> <%= @user.name %></h5>
        <h5><strong>Email:</strong> <%= @user.email %></h5>
      </div>

      <div>
        <%= link_to raw('<i class="fa-solid fa-pen-to-square fa-2xl" style="color: #f4e32a;"></i>'), edit_user_path(@user), class: "btn ps-0", title: "Edit" %>
        <%= link_to raw('<i class="fa-solid fa-trash-can fa-2xl" style="color: #f02828;"></i>'), user_path(@user), class: "btn", title: "Remove", data: { turbo_method: :delete, turbo_confirm: :"Are You Sure?" } %>
        <%= link_to raw('<i class="fa-solid fa-list fa-2xl" style="color: #12e4f3;"></i>'), users_path, :class => 'btn', title: "All" %>
      </div>
    </div>
  </div>

  <div class="mt-5">
    <table class="table container table-hover table-striped">
      <thead>
        <tr>
          <th>Event</th>
          <th>Date</th>
          <th>Enrollments</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "event", collection: @events %>
      </tbody>
    </table>
  </div>
</div>